const APP_URL_KEY='pemilih_muda_web_app_url';let installPrompt=null;
const toast=document.getElementById('toast'),urlInput=document.getElementById('web-app-url'),openButton=document.getElementById('open-app'),installButton=document.getElementById('install-app');
function notify(message){toast.textContent=message;toast.classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>toast.classList.remove('show'),3000)}
function validWebAppUrl(value){try{const url=new URL(value);return url.protocol==='https:'&&url.hostname==='script.google.com'&&url.pathname.endsWith('/exec');}catch(error){return false;}}
function savedUrl(){return localStorage.getItem(APP_URL_KEY)||''}urlInput.value=savedUrl();
document.getElementById('url-form').addEventListener('submit',event=>{event.preventDefault();const value=urlInput.value.trim();if(!validWebAppUrl(value)){notify('Gunakan URL HTTPS script.google.com yang berakhiran /exec.');return}localStorage.setItem(APP_URL_KEY,value);notify('Web App berhasil dihubungkan.')});
openButton.addEventListener('click',()=>{const value=savedUrl();if(!validWebAppUrl(value)){document.getElementById('setup').scrollIntoView({behavior:'smooth'});notify('Hubungkan URL Web App terlebih dahulu.');return}window.open(value,'_blank','noopener,noreferrer')});
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;installButton.hidden=false});installButton.addEventListener('click',async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;installButton.hidden=true});window.addEventListener('appinstalled',()=>{installButton.hidden=true;notify('PEMILIH MUDA berhasil diinstall.')});
function networkState(){const online=navigator.onLine,indicator=document.getElementById('network');indicator.textContent=online?'ONLINE':'OFFLINE';indicator.classList.toggle('offline',!online)}window.addEventListener('online',networkState);window.addEventListener('offline',networkState);networkState();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js').catch(()=>notify('Offline shell belum aktif.')));
