const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const context = {};
vm.createContext(context);
vm.runInContext(fs.readFileSync('src/Utility.gs','utf8') + '\n' + fs.readFileSync('src/ValidationService.gs','utf8') + '\nthis.validate=validateRegistration_;this.email=normalizeEmail_;this.nis=normalizeNis_;this.phone=normalizePhone_;', context);
assert.equal(context.email('  SISWA@Example.COM '), 'siswa@example.com');
assert.equal(context.nis(' 12 34-5 '), '1234-5');
assert.equal(context.phone('+62 812-3456-7890'), '081234567890');
assert.equal(context.isIsoDate_('2024-02-29'), true);
assert.equal(context.isIsoDate_('2026-02-31'), false);
assert.equal(context.constantTimeEqual_('hash-value', 'hash-value'), true);
assert.equal(context.constantTimeEqual_('hash-value', 'hash-other'), false);
const valid = context.validate({name:'Ahmad Pratama',nis:'1234567890',schoolId:'SCH_1234567890abcdef1234',className:'XII IPA 1',birthDate:'2008-02-29',gender:'LAKI-LAKI',whatsapp:'081234567890',email:'ahmad@example.id',password:'PemilihMuda2026',agreement:true});
assert.equal(valid.valid, true, valid.errors.join(' '));
const invalid = context.validate({name:'A',nis:'1',schoolId:'bebas',className:'',birthDate:'x',whatsapp:'abc',email:'x',password:'pendek',agreement:false});
assert.equal(invalid.valid, false);
assert.ok(invalid.errors.length >= 7);
const season = context.validateSeason_({name:'Agustus 2026',theme:'Hak Pilih',startDate:'2026-08-01',endDate:'2026-08-31',status:'DRAFT',questionCount:25,pointPerQuestion:10,maxAttempt:1,durationSeconds:1800,showExplanation:'AFTER_ANSWER'});
assert.equal(season.valid, true, season.errors.join(' '));
assert.equal(context.validateSeason_({name:'X',theme:'',startDate:'2026-09-01',endDate:'2026-08-01',status:'ACTIVE',questionCount:0,pointPerQuestion:-1,maxAttempt:0,durationSeconds:10}).valid, false);
const question = context.validateQuestion_({category:'Demokrasi',question:'Mengapa pilihan politik perlu dihormati?',optionA:'Karena merupakan hak warga',optionB:'Karena wajib sama',optionC:'Karena tanpa aturan',optionD:'Karena bersifat acak',correctAnswer:'A',explanation:'Pilihan adalah hak warga.',difficulty:'EASY',point:10,status:'ACTIVE'});
assert.equal(question.valid, true, question.errors.join(' '));
assert.equal(context.validateQuestion_({category:'',question:'Pendek',optionA:'Sama',optionB:'Sama',optionC:'',optionD:'',correctAnswer:'E',difficulty:'X',point:-1,status:'X'}).valid, false);
console.log('Validation checks passed');
