function getAdminDashboard(adminToken){
  try{const auth=requireSession_(adminToken,['ADMIN','SUPERADMIN']),users=readTable_('Users'),students=users.filter(item=>item.Role==='STUDENT'),schools=readTable_('Schools'),sessions=readTable_('QuizSessions'),season=resolveActiveSeason_(),today=Utilities.formatDate(new Date(),APP.TIME_ZONE,'yyyy-MM-dd'),recent=readTable_('ActivityLogs').sort((a,b)=>String(b.Timestamp).localeCompare(String(a.Timestamp))).slice(0,10).map(item=>({action:item.Action,entity:item.Entity,description:item.Description,timestamp:item.Timestamp}));return apiSuccess_({admin:{name:auth.user.Name,role:auth.user.Role},stats:{participants:students.length,activeParticipants:students.filter(item=>item.Status==='ACTIVE').length,pendingParticipants:students.filter(item=>item.Status==='PENDING').length,schools:schools.filter(item=>item.Status==='ACTIVE').length,completedQuiz:sessions.filter(item=>item.Status==='COMPLETED').length,activeSeason:season?season.NamaSeason:'Tidak ada'},recentActivity:recent,date:today});}catch(error){return apiError_(error.message,error.publicCode||'ADMIN_DASHBOARD_FAILED');}
}

function listParticipants(adminToken,filter){
  try{requireSession_(adminToken,['ADMIN','SUPERADMIN']);const query=filter||{},search=sanitizeText_(query.search,100).toLowerCase(),schoolId=sanitizeText_(query.schoolId,40),status=sanitizeText_(query.status,20).toUpperCase(),page=Math.max(1,Number(query.page)||1),pageSize=Math.min(100,Math.max(1,Number(query.pageSize)||25)),schools=readTable_('Schools').reduce((map,item)=>{map[item.SchoolID]=item;return map;},{});let rows=readTable_('Users').filter(item=>item.Role==='STUDENT');if(search)rows=rows.filter(item=>[item.Name,item.NIS,item.Email,item.WhatsApp].some(value=>String(value).toLowerCase().indexOf(search)>=0));if(schoolId)rows=rows.filter(item=>item.SchoolID===schoolId);if(status)rows=rows.filter(item=>item.Status===status);rows.sort((a,b)=>String(b.CreatedAt).localeCompare(String(a.CreatedAt)));return apiSuccess_({participants:rows.slice((page-1)*pageSize,page*pageSize).map(item=>({userId:item.UserID,name:item.Name,nis:item.NIS,schoolId:item.SchoolID,school:schools[item.SchoolID]?schools[item.SchoolID].NamaSekolah:'',district:schools[item.SchoolID]?schools[item.SchoolID].Kecamatan:'',className:item.Class,whatsapp:item.WhatsApp,email:item.Email,status:item.Status,point:Number(item.TotalPointCache||0),fraudScore:Number(item.FraudScore||0),createdAt:item.CreatedAt})),total:rows.length,page:page,pageSize:pageSize});}catch(error){return apiError_(error.message,error.publicCode||'PARTICIPANTS_FAILED');}
}

function setParticipantStatus(adminToken,userId,status,reason){
  try{const admin=requireSession_(adminToken,['ADMIN','SUPERADMIN']),id=sanitizeText_(userId,40),value=sanitizeText_(status,20).toUpperCase(),note=sanitizeText_(reason,500),user=findOne_('Users','UserID',id);if(!user||user.Role!=='STUDENT')return apiError_('Peserta tidak ditemukan.','USER_NOT_FOUND');if(['ACTIVE','PENDING','SUSPENDED','BLOCKED'].indexOf(value)<0)return apiError_('Status tidak valid.','VALIDATION_ERROR');if(['SUSPENDED','BLOCKED'].indexOf(value)>=0&&note.length<5)return apiError_('Alasan suspend/block wajib diisi.','REASON_REQUIRED');updateRecord_('Users','UserID',id,{Status:value,UpdatedAt:nowIso_()});if(value!=='ACTIVE')revokeUserSessions_(id);logActivity_(admin.user.UserID,'ADMIN_UPDATE','Users',id,'Status peserta menjadi '+value+(note?' — '+note:''),'');return apiSuccess_({},'Status peserta diperbarui.');}catch(error){return apiError_(error.message,error.publicCode||'PARTICIPANT_STATUS_FAILED');}
}
