const APP = Object.freeze({
  NAME: 'PEMILIH MUDA',
  VERSION: '0.14.1',
  SCHEMA_VERSION: '1',
  TIME_ZONE: 'Asia/Jakarta',
  DATABASE_PROPERTY: 'DATABASE_SPREADSHEET_ID',
  DRIVE_FOLDER_PROPERTY: 'APP_DRIVE_FOLDER_ID',
  PASSWORD_PEPPER_PROPERTY: 'PASSWORD_PEPPER',
  DEFAULT_ADMIN_EMAIL_PROPERTY: 'DEFAULT_ADMIN_EMAIL',
  DEFAULT_ADMIN_PASSWORD_PROPERTY: 'DEFAULT_ADMIN_PASSWORD',
  CACHE_SECONDS: 300,
  SESSION_HOURS: 12,
  LOGIN_LIMIT: 5,
  LOGIN_WINDOW_SECONDS: 600
});

const ENUMS = Object.freeze({
  ROLE: ['STUDENT', 'ADMIN', 'SUPERADMIN'],
  USER_STATUS: ['ACTIVE', 'PENDING', 'SUSPENDED', 'BLOCKED'],
  SEASON_STATUS: ['DRAFT', 'SCHEDULED', 'ACTIVE', 'FINISHED', 'ARCHIVED'],
  SESSION_STATUS: ['STARTED', 'COMPLETED', 'EXPIRED', 'INVALID'],
  POINT_SOURCE: ['QUIZ', 'BONUS', 'ACHIEVEMENT', 'ADMIN', 'PENALTY'],
  RECORD_STATUS: ['ACTIVE', 'INACTIVE', 'VALID', 'INVALID'],
  REWARD_STATUS: ['WAITING', 'VERIFIED', 'SENT', 'COMPLETED']
});

const DEFAULT_SETTINGS = Object.freeze({
  APP_NAME: APP.NAME,
  APP_VERSION: APP.VERSION,
  SCHEMA_VERSION: APP.SCHEMA_VERSION,
  REGISTRATION_OPEN: 'TRUE',
  ACTIVE_SEASON: '',
  DEFAULT_QUESTION_POINT: '10',
  QUIZ_MAX_ATTEMPT: '1',
  QUIZ_TIME_LIMIT: '1800',
  COMPLETE_QUIZ_BONUS: '0',
  PERFECT_SCORE_BONUS: '50',
  SHOW_LEADERBOARD: 'TRUE',
  SHOW_SCHOOL_RANK: 'TRUE',
  ENABLE_ACHIEVEMENT: 'TRUE',
  MASK_PUBLIC_NAME: 'TRUE',
  MAINTENANCE_MODE: 'FALSE'
});
