const FRAUD_RULES=Object.freeze({DUPLICATE_IDENTITY:30,SHARED_DEVICE:10,UNREALISTIC_DURATION:25,EXCESSIVE_REQUESTS:15,ANSWER_REPLAY:15,NONCE_INVALID:20,OPTION_INVALID:20,PARAMETER_MANIPULATION:20});
function riskLevel_(score){const value=Number(score||0);return value>=51?'HIGH RISK':value>=21?'REVIEW':'NORMAL';}
function recalculateFraudScore_(userId){const score=readTable_('FraudLogs').filter(item=>item.UserID===userId&&item.Status!=='DISMISSED').reduce((sum,item)=>sum+Number(item.Score||0),0);updateRecord_('Users','UserID',userId,{FraudScore:score,UpdatedAt:nowIso_()});return score;}
function recordFraudOnce_(userId,sessionId,ruleCode,description,evidence){const rule=sanitizeText_(ruleCode,50).toUpperCase(),session=sanitizeText_(sessionId,50),existing=readTable_('FraudLogs').find(item=>item.UserID===userId&&item.SessionID===session&&item.RuleCode===rule&&item.Status!=='DISMISSED');if(existing)return existing;const score=Number(FRAUD_RULES[rule]||10),record={FraudLogID:generateId_('FraudLogs'),UserID:userId,SessionID:session,RuleCode:rule,Score:score,RiskLevel:riskLevel_(score),Description:sanitizeText_(description,500),Evidence:safeJson_(evidence||{}),Status:'OPEN',CreatedAt:nowIso_(),ReviewedAt:'',ReviewedBy:''};appendRecords_('FraudLogs',[record]);const total=recalculateFraudScore_(userId);updateRecord_('FraudLogs','FraudLogID',record.FraudLogID,{RiskLevel:riskLevel_(total)});return record;}
function checkActionRate_(userId,action,limit,windowSeconds){const cache=CacheService.getScriptCache(),key='rate:'+userId+':'+action,count=Number(cache.get(key)||0);cache.put(key,String(count+1),windowSeconds);if(count>=limit){const bucket=Math.floor(Date.now()/(windowSeconds*1000));recordFraudOnce_(userId,'RATE_'+action+'_'+bucket,'EXCESSIVE_REQUESTS','Request berlebihan pada '+action,{count:count+1,windowSeconds:windowSeconds});return false;}return true;}

function scanFraudSignals(adminToken){try{const admin=requireSession_(adminToken,['ADMIN','SUPERADMIN']);return withDocumentLock_(function(){const users=readTable_('Users').filter(item=>item.Role==='STUDENT'),sessions=readTable_('QuizSessions'),identityGroups={},deviceGroups={};users.forEach(user=>{[['NIS',normalizeNis_(user.NIS)],['EMAIL',normalizeEmail_(user.Email)]].forEach(pair=>{if(!pair[1])return;const key=pair[0]+':'+pair[1];if(!identityGroups[key])identityGroups[key]=[];identityGroups[key].push(user.UserID);});});sessions.filter(item=>item.DeviceID).forEach(item=>{if(!deviceGroups[item.DeviceID])deviceGroups[item.DeviceID]=new Set();deviceGroups[item.DeviceID].add(item.UserID);});let detected=0;Object.keys(identityGroups).filter(key=>identityGroups[key].length>1).forEach(key=>identityGroups[key].forEach(userId=>{recordFraudOnce_(userId,'IDENTITY_'+key,'DUPLICATE_IDENTITY','Identitas digunakan pada lebih dari satu akun',{identityType:key.split(':')[0],accounts:identityGroups[key].length});detected++;}));Object.keys(deviceGroups).filter(device=>deviceGroups[device].size>1).forEach(device=>Array.from(deviceGroups[device]).forEach(userId=>{recordFraudOnce_(userId,'DEVICE_'+device.slice(0,24),'SHARED_DEVICE','Perangkat digunakan oleh beberapa akun; perlu review manual',{accounts:deviceGroups[device].size});detected++;}));logActivity_(admin.user.UserID,'ADMIN_UPDATE','FraudLogs','SCAN','Pemindaian fraud selesai: '+detected+' sinyal','');return apiSuccess_({signals:detected},'Pemindaian fraud selesai.');});}catch(error){return apiError_(error.message,error.publicCode||'FRAUD_SCAN_FAILED');}}

function listFraudCases(adminToken,filter){try{requireSession_(adminToken,['ADMIN','SUPERADMIN']);const query=filter||{},status=sanitizeText_(query.status,20).toUpperCase(),risk=sanitizeText_(query.risk,20).toUpperCase(),users=readTable_('Users').reduce((map,item)=>{map[item.UserID]=item;return map;},{});let rows=readTable_('FraudLogs');if(status)rows=rows.filter(item=>item.Status===status);if(risk)rows=rows.filter(item=>item.RiskLevel===risk);rows.sort((a,b)=>String(b.CreatedAt).localeCompare(String(a.CreatedAt)));return apiSuccess_({cases:rows.slice(0,200).map(item=>({fraudLogId:item.FraudLogID,userId:item.UserID,userName:users[item.UserID]?users[item.UserID].Name:'',ruleCode:item.RuleCode,score:Number(item.Score),totalScore:users[item.UserID]?Number(users[item.UserID].FraudScore||0):0,riskLevel:users[item.UserID]?riskLevel_(users[item.UserID].FraudScore):item.RiskLevel,description:item.Description,evidence:item.Evidence,status:item.Status,createdAt:item.CreatedAt}))});}catch(error){return apiError_(error.message,error.publicCode||'FRAUD_CASES_FAILED');}}

function reviewFraudCase(adminToken,fraudLogId,decision){try{const admin=requireSession_(adminToken,['ADMIN','SUPERADMIN']),id=sanitizeText_(fraudLogId,40),value=sanitizeText_(decision,20).toUpperCase(),record=findOne_('FraudLogs','FraudLogID',id);if(!record)return apiError_('Fraud log tidak ditemukan.','FRAUD_NOT_FOUND');if(['CONFIRMED','DISMISSED'].indexOf(value)<0)return apiError_('Keputusan review tidak valid.','VALIDATION_ERROR');updateRecord_('FraudLogs','FraudLogID',id,{Status:value,ReviewedAt:nowIso_(),ReviewedBy:admin.user.UserID});const total=recalculateFraudScore_(record.UserID);logActivity_(admin.user.UserID,'ADMIN_UPDATE','FraudLogs',id,'Review fraud: '+value,'');return apiSuccess_({fraudScore:total,riskLevel:riskLevel_(total)},'Fraud case berhasil direview.');}catch(error){return apiError_(error.message,error.publicCode||'FRAUD_REVIEW_FAILED');}}
