function validateMaterial_(payload){const data=payload||{},clean={title:sanitizeText_(data.title,180),category:sanitizeText_(data.category,100),thumbnail:sanitizeText_(data.thumbnail,500),content:sanitizeMultiline_(data.content,30000),videoUrl:sanitizeText_(data.videoUrl,500),status:sanitizeText_(data.status||'DRAFT',20).toUpperCase()},errors=[];if(clean.title.length<4)errors.push('Judul materi minimal 4 karakter.');if(!clean.category)errors.push('Kategori materi wajib diisi.');if(clean.content.length<20&&!clean.videoUrl)errors.push('Isi materi minimal 20 karakter atau sertakan video.');if(clean.thumbnail&&!/^https:\/\//i.test(clean.thumbnail))errors.push('Thumbnail harus menggunakan HTTPS.');if(clean.videoUrl&&!/^https:\/\//i.test(clean.videoUrl))errors.push('URL video harus menggunakan HTTPS.');if(['DRAFT','PUBLISHED','ARCHIVED'].indexOf(clean.status)<0)errors.push('Status materi tidak valid.');return {valid:!errors.length,errors:errors,data:clean};}

function materialRecord_(data,id,existing){const timestamp=nowIso_();return {MaterialID:id,Title:data.title,Category:data.category,Thumbnail:data.thumbnail,Content:data.content,VideoURL:data.videoUrl,Status:data.status,PublishedAt:data.status==='PUBLISHED'?(existing&&existing.PublishedAt||timestamp):existing&&existing.PublishedAt||'',CreatedAt:existing&&existing.CreatedAt||timestamp,UpdatedAt:timestamp};}

function listMaterials(adminToken){try{requireSession_(adminToken,['ADMIN','SUPERADMIN']);return apiSuccess_({materials:readTable_('Materials').sort((a,b)=>String(b.UpdatedAt).localeCompare(String(a.UpdatedAt)))});}catch(error){return apiError_(error.message,error.publicCode||'MATERIALS_FAILED');}}
function createMaterial(adminToken,payload){try{const admin=requireSession_(adminToken,['ADMIN','SUPERADMIN']),result=validateMaterial_(payload);if(!result.valid)return apiError_(result.errors[0],'VALIDATION_ERROR');const id=generateId_('Materials');appendRecords_('Materials',[materialRecord_(result.data,id,null)]);CacheService.getScriptCache().remove('publicMaterials');logActivity_(admin.user.UserID,'ADMIN_UPDATE','Materials',id,'Membuat materi','');return apiSuccess_({materialId:id},'Materi berhasil dibuat.');}catch(error){return apiError_(error.message,error.publicCode||'MATERIAL_CREATE_FAILED');}}
function updateMaterial(adminToken,materialId,payload){try{const admin=requireSession_(adminToken,['ADMIN','SUPERADMIN']),id=sanitizeText_(materialId,40),existing=findOne_('Materials','MaterialID',id);if(!existing)return apiError_('Materi tidak ditemukan.','MATERIAL_NOT_FOUND');const result=validateMaterial_(payload);if(!result.valid)return apiError_(result.errors[0],'VALIDATION_ERROR');updateRecord_('Materials','MaterialID',id,materialRecord_(result.data,id,existing));CacheService.getScriptCache().remove('publicMaterials');logActivity_(admin.user.UserID,'ADMIN_UPDATE','Materials',id,'Memperbarui materi','');return apiSuccess_({},'Materi berhasil diperbarui.');}catch(error){return apiError_(error.message,error.publicCode||'MATERIAL_UPDATE_FAILED');}}
function setMaterialStatus(adminToken,materialId,status){try{const admin=requireSession_(adminToken,['ADMIN','SUPERADMIN']),id=sanitizeText_(materialId,40),value=sanitizeText_(status,20).toUpperCase();if(['DRAFT','PUBLISHED','ARCHIVED'].indexOf(value)<0)return apiError_('Status tidak valid.','VALIDATION_ERROR');const material=findOne_('Materials','MaterialID',id);if(!material)return apiError_('Materi tidak ditemukan.','MATERIAL_NOT_FOUND');updateRecord_('Materials','MaterialID',id,{Status:value,PublishedAt:value==='PUBLISHED'?(material.PublishedAt||nowIso_()):material.PublishedAt,UpdatedAt:nowIso_()});CacheService.getScriptCache().remove('publicMaterials');logActivity_(admin.user.UserID,'ADMIN_UPDATE','Materials',id,'Status materi menjadi '+value,'');return apiSuccess_({},'Status materi diperbarui.');}catch(error){return apiError_(error.message,error.publicCode||'MATERIAL_STATUS_FAILED');}}
function getPublicMaterials(limit){try{const cache=CacheService.getScriptCache(),cached=cache.get('publicMaterials');let rows=cached?JSON.parse(cached):readTable_('Materials').filter(item=>item.Status==='PUBLISHED').sort((a,b)=>String(b.PublishedAt).localeCompare(String(a.PublishedAt))).map(item=>({id:item.MaterialID,title:item.Title,category:item.Category,thumbnail:item.Thumbnail||'',excerpt:String(item.Content||'').slice(0,180),videoUrl:item.VideoURL||'',publishedAt:item.PublishedAt}));if(!cached)cache.put('publicMaterials',JSON.stringify(rows),APP.CACHE_SECONDS);return apiSuccess_({materials:rows.slice(0,Math.min(20,Math.max(1,Number(limit)||6)))});}catch(error){return apiError_('Materi belum tersedia.','PUBLIC_MATERIALS_FAILED');}}
function getPublicMaterial(materialId){try{const item=findOne_('Materials','MaterialID',sanitizeText_(materialId,40));if(!item||item.Status!=='PUBLISHED')return apiError_('Materi tidak ditemukan.','MATERIAL_NOT_FOUND');return apiSuccess_({material:{id:item.MaterialID,title:item.Title,category:item.Category,thumbnail:item.Thumbnail||'',content:item.Content,videoUrl:item.VideoURL||'',publishedAt:item.PublishedAt}});}catch(error){return apiError_('Materi tidak dapat dibuka.','MATERIAL_FAILED');}}
