function questionRecord_(data,id,createdAt){const timestamp=nowIso_();return {QuestionID:id,Kategori:data.category,Pertanyaan:data.question,PilihanA:data.optionA,PilihanB:data.optionB,PilihanC:data.optionC,PilihanD:data.optionD,JawabanBenar:data.correctAnswer,Pembahasan:data.explanation,Difficulty:data.difficulty,Point:data.point,Status:data.status,CreatedAt:createdAt||timestamp,UpdatedAt:timestamp};}

function listQuestions(adminToken,filter){
  try{requireSession_(adminToken,['ADMIN','SUPERADMIN']);const query=filter||{},category=sanitizeText_(query.category,100).toLowerCase(),status=sanitizeText_(query.status,20).toUpperCase(),search=sanitizeText_(query.search,100).toLowerCase(),page=Math.max(1,Number(query.page)||1),pageSize=Math.min(100,Math.max(1,Number(query.pageSize)||25));let rows=readTable_('Questions');if(category)rows=rows.filter(item=>String(item.Kategori).toLowerCase()===category);if(status)rows=rows.filter(item=>item.Status===status);if(search)rows=rows.filter(item=>String(item.Pertanyaan).toLowerCase().indexOf(search)>=0);return apiSuccess_({questions:rows.slice((page-1)*pageSize,page*pageSize),total:rows.length,page:page,pageSize:pageSize});}catch(error){return apiError_(error.message,error.publicCode||'QUESTION_LIST_FAILED');}
}

function createQuestion(adminToken,payload){try{const admin=requireSession_(adminToken,['ADMIN','SUPERADMIN']),result=validateQuestion_(payload);if(!result.valid)return apiError_(result.errors[0],'VALIDATION_ERROR');const id=generateId_('Questions');appendRecords_('Questions',[questionRecord_(result.data,id)]);logActivity_(admin.user.UserID,'ADMIN_UPDATE','Questions',id,'Membuat soal','');return apiSuccess_({questionId:id},'Soal berhasil dibuat.');}catch(error){return apiError_(error.publicCode?error.message:'Soal gagal dibuat.',error.publicCode||'QUESTION_CREATE_FAILED');}}

function updateQuestion(adminToken,questionId,payload){try{const admin=requireSession_(adminToken,['ADMIN','SUPERADMIN']),id=sanitizeText_(questionId,40),existing=findOne_('Questions','QuestionID',id);if(!existing)return apiError_('Soal tidak ditemukan.','QUESTION_NOT_FOUND');const result=validateQuestion_(payload);if(!result.valid)return apiError_(result.errors[0],'VALIDATION_ERROR');updateRecord_('Questions','QuestionID',id,questionRecord_(result.data,id,existing.CreatedAt));logActivity_(admin.user.UserID,'ADMIN_UPDATE','Questions',id,'Memperbarui soal','');return apiSuccess_({},'Soal berhasil diperbarui.');}catch(error){return apiError_(error.message,error.publicCode||'QUESTION_UPDATE_FAILED');}}

function setQuestionStatus(adminToken,questionId,status){try{const admin=requireSession_(adminToken,['ADMIN','SUPERADMIN']),id=sanitizeText_(questionId,40),value=sanitizeText_(status,20).toUpperCase();if(['ACTIVE','INACTIVE'].indexOf(value)<0)return apiError_('Status tidak valid.','VALIDATION_ERROR');if(!updateRecord_('Questions','QuestionID',id,{Status:value,UpdatedAt:nowIso_()}))return apiError_('Soal tidak ditemukan.','QUESTION_NOT_FOUND');logActivity_(admin.user.UserID,'ADMIN_UPDATE','Questions',id,'Mengubah status soal menjadi '+value,'');return apiSuccess_({},'Status soal diperbarui.');}catch(error){return apiError_(error.message,error.publicCode||'QUESTION_STATUS_FAILED');}}

function duplicateQuestion(adminToken,questionId){try{const admin=requireSession_(adminToken,['ADMIN','SUPERADMIN']),source=findOne_('Questions','QuestionID',sanitizeText_(questionId,40));if(!source)return apiError_('Soal tidak ditemukan.','QUESTION_NOT_FOUND');const id=generateId_('Questions'),timestamp=nowIso_(),copy=Object.assign({},source,{QuestionID:id,Pertanyaan:source.Pertanyaan+' (Salinan)',Status:'INACTIVE',CreatedAt:timestamp,UpdatedAt:timestamp});appendRecords_('Questions',[copy]);logActivity_(admin.user.UserID,'ADMIN_UPDATE','Questions',id,'Duplikasi soal dari '+source.QuestionID,'');return apiSuccess_({questionId:id},'Soal berhasil diduplikasi.');}catch(error){return apiError_(error.message,error.publicCode||'QUESTION_DUPLICATE_FAILED');}}

function importQuestionsFromSpreadsheet(adminToken,spreadsheetId,sheetName){
  try{const admin=requireSession_(adminToken,['ADMIN','SUPERADMIN']),id=sanitizeText_(spreadsheetId,100),name=sanitizeText_(sheetName||'Questions',100),source=SpreadsheetApp.openById(id).getSheetByName(name);if(!source)return apiError_('Sheet sumber tidak ditemukan.','IMPORT_SHEET_NOT_FOUND');const values=source.getDataRange().getValues();if(values.length<2)return apiError_('Sheet sumber tidak memiliki data.','IMPORT_EMPTY');if(values.length>1001)return apiError_('Import maksimal 1.000 soal per proses.','IMPORT_LIMIT');const headers=values[0].map(value=>String(value).trim()),required=['Kategori','Pertanyaan','PilihanA','PilihanB','PilihanC','PilihanD','JawabanBenar','Pembahasan','Difficulty','Point','Status'];if(required.some(header=>headers.indexOf(header)<0))return apiError_('Header import tidak lengkap.','IMPORT_HEADERS_INVALID');const existing=new Set(readTable_('Questions').map(item=>String(item.Pertanyaan).trim().toLowerCase())),records=[],summary={success:0,duplicate:0,invalid:0};values.slice(1).forEach(row=>{const raw={};headers.forEach((header,index)=>raw[header]=row[index]);const key=String(raw.Pertanyaan||'').trim().toLowerCase();if(existing.has(key)){summary.duplicate++;return;}const result=validateQuestion_({category:raw.Kategori,question:raw.Pertanyaan,optionA:raw.PilihanA,optionB:raw.PilihanB,optionC:raw.PilihanC,optionD:raw.PilihanD,correctAnswer:raw.JawabanBenar,explanation:raw.Pembahasan,difficulty:raw.Difficulty,point:raw.Point,status:raw.Status});if(!result.valid){summary.invalid++;return;}existing.add(key);records.push(questionRecord_(result.data,generateId_('Questions')));summary.success++;});appendRecords_('Questions',records);logActivity_(admin.user.UserID,'ADMIN_UPDATE','Questions','IMPORT','Import soal: '+safeJson_(summary),'');return apiSuccess_(summary,'Import soal selesai.');}catch(error){console.error(error);return apiError_(error.publicCode?error.message:'Import soal gagal. Periksa akses Spreadsheet.',error.publicCode||'QUESTION_IMPORT_FAILED');}
}
