const REPORT_TYPES=Object.freeze(['PARTICIPANTS','SCHOOLS','QUIZ','LEADERBOARD','SEASONS','WINNERS','REWARDS','FRAUD','POINT_TRANSACTIONS']);
function csvCell_(value){let text=value instanceof Date?Utilities.formatDate(value,APP.TIME_ZONE,"yyyy-MM-dd HH:mm:ss"):String(value==null?'':value);if(/^[=+\-@]/.test(text.trim()))text="'"+text;return '"'+text.replace(/"/g,'""')+'"';}
function csvFromRows_(headers,rows){return '\uFEFF'+[headers].concat(rows).map(row=>row.map(csvCell_).join(',')).join('\r\n');}
function reportContext_(){const users=readTable_('Users'),schools=readTable_('Schools'),seasons=readTable_('Seasons');return {users:users,userMap:users.reduce((map,item)=>{map[item.UserID]=item;return map;},{}),schools:schools,schoolMap:schools.reduce((map,item)=>{map[item.SchoolID]=item;return map;},{}),seasons:seasons,seasonMap:seasons.reduce((map,item)=>{map[item.SeasonID]=item;return map;},{})};}
function reportData_(type,filters){
  const context=reportContext_(),seasonId=sanitizeText_((filters||{}).seasonId,40),matchSeason=item=>!seasonId||item.SeasonID===seasonId;
  if(type==='PARTICIPANTS')return {headers:['UserID','Nama','NIS/NISN','Sekolah','Kelas','Tanggal Lahir','Gender','WhatsApp','Email','Status','Total Point','Fraud Score','Tanggal Daftar'],rows:context.users.filter(item=>item.Role==='STUDENT').map(item=>[item.UserID,item.Name,item.NIS,context.schoolMap[item.SchoolID]?context.schoolMap[item.SchoolID].NamaSekolah:'',item.Class,item.BirthDate,item.Gender,item.WhatsApp,item.Email,item.Status,item.TotalPointCache,item.FraudScore,item.CreatedAt])};
  if(type==='SCHOOLS'){const users=context.users.filter(item=>item.Role==='STUDENT'),sessions=readTable_('QuizSessions').filter(item=>item.Status==='COMPLETED'&&matchSeason(item));return {headers:['SchoolID','Nama Sekolah','NPSN','Jenis','Alamat','Kecamatan','Status','Jumlah Peserta','Quiz Selesai'],rows:context.schools.map(item=>[item.SchoolID,item.NamaSekolah,item.NPSN,item.Jenis,item.Alamat,item.Kecamatan,item.Status,users.filter(user=>user.SchoolID===item.SchoolID).length,sessions.filter(session=>{const user=context.userMap[session.UserID];return user&&user.SchoolID===item.SchoolID;}).length])};}
  if(type==='QUIZ')return {headers:['SessionID','Peserta','Sekolah','Season','Mulai','Selesai','Benar','Salah','Score','Bonus','Total Point','Durasi','Status','DeviceID'],rows:readTable_('QuizSessions').filter(matchSeason).map(item=>{const user=context.userMap[item.UserID]||{},school=context.schoolMap[user.SchoolID]||{},season=context.seasonMap[item.SeasonID]||{};return [item.SessionID,user.Name,school.NamaSekolah,season.NamaSeason,item.StartedAt,item.FinishedAt,item.Correct,item.Wrong,item.Score,item.Bonus,item.TotalPoint,item.Duration,item.Status,item.DeviceID];})};
  if(type==='LEADERBOARD'){const season=seasonId?context.seasonMap[seasonId]:resolveActiveSeason_(),rows=season?buildLeaderboard_(season.SeasonID):[];return {headers:['Ranking','Nama Peserta','Sekolah','Total Point','Season'],rows:rows.map(item=>[item.rank,item.name,item.school,item.point,season.NamaSeason])};}
  if(type==='SEASONS')return {headers:['SeasonID','Nama','Tema','Mulai','Selesai','Status','Reward','Jumlah Soal','Point/Soal','Max Attempt','Durasi'],rows:context.seasons.filter(matchSeason).map(item=>[item.SeasonID,item.NamaSeason,item.Tema,item.TanggalMulai,item.TanggalSelesai,item.Status,item.Reward,item.JumlahSoal,item.PoinPerSoal,item.MaxAttempt,item.DurasiQuiz])};
  if(type==='WINNERS')return {headers:['WinnerID','Season','Nama','Sekolah','Rank','Point','Reward','Status Reward','Keputusan','Catatan','Dipilih Pada','Dipilih Oleh'],rows:readTable_('Winners').filter(matchSeason).map(item=>{const user=context.userMap[item.UserID]||{},school=context.schoolMap[user.SchoolID]||{},season=context.seasonMap[item.SeasonID]||{},admin=context.userMap[item.SelectedBy]||{};return [item.WinnerID,season.NamaSeason,user.Name,school.NamaSekolah,item.Rank,item.Point,item.Reward,item.StatusReward,item.SelectionStatus,item.ReviewNote,item.SelectedAt,admin.Name];})};
  if(type==='REWARDS'){const winnerMap=readTable_('Winners').reduce((map,item)=>{map[item.WinnerID]=item;return map;},{});return {headers:['RewardID','Season','Pemenang','Nama Reward','Nominal','Nomor Tujuan','Provider','Status','Tanggal Kirim','Catatan'],rows:readTable_('Rewards').filter(matchSeason).map(item=>{const winner=winnerMap[item.WinnerID]||{},user=context.userMap[winner.UserID]||{},season=context.seasonMap[item.SeasonID]||{};return [item.RewardID,season.NamaSeason,user.Name,item.NamaReward,item.Nominal,item.NomorTujuan,item.Provider,item.Status,item.TanggalKirim,item.Catatan];})};}
  if(type==='FRAUD')return {headers:['FraudLogID','Peserta','Rule','Score','Total Fraud Score','Risk','Deskripsi','Evidence','Status','Dibuat','Direview'],rows:readTable_('FraudLogs').map(item=>{const user=context.userMap[item.UserID]||{};return [item.FraudLogID,user.Name,item.RuleCode,item.Score,user.FraudScore,item.RiskLevel,item.Description,item.Evidence,item.Status,item.CreatedAt,item.ReviewedAt];})};
  if(type==='POINT_TRANSACTIONS')return {headers:['PointID','Peserta','Season','Source Type','Source ID','Point','Deskripsi','Dibuat','Status'],rows:readTable_('PointTransactions').filter(matchSeason).map(item=>{const user=context.userMap[item.UserID]||{},season=context.seasonMap[item.SeasonID]||{};return [item.PointID,user.Name,season.NamaSeason,item.SourceType,item.SourceID,item.Point,item.Description,item.CreatedAt,item.Status];})};
  throw authError_('Jenis laporan tidak valid.','REPORT_TYPE_INVALID');
}
function getReportPreview(adminToken,type,filters){try{requireSession_(adminToken,['ADMIN','SUPERADMIN']);const value=sanitizeText_(type,30).toUpperCase();if(REPORT_TYPES.indexOf(value)<0)return apiError_('Jenis laporan tidak valid.','REPORT_TYPE_INVALID');const data=reportData_(value,filters||{});return apiSuccess_({type:value,headers:data.headers,rows:data.rows.slice(0,200),total:data.rows.length,truncated:data.rows.length>200});}catch(error){return apiError_(error.message,error.publicCode||'REPORT_PREVIEW_FAILED');}}
function exportReportCsv(adminToken,type,filters){try{const admin=requireSession_(adminToken,['ADMIN','SUPERADMIN']),value=sanitizeText_(type,30).toUpperCase();if(REPORT_TYPES.indexOf(value)<0)return apiError_('Jenis laporan tidak valid.','REPORT_TYPE_INVALID');const data=reportData_(value,filters||{});if(data.rows.length>50000)return apiError_('Laporan melebihi 50.000 baris. Gunakan filter yang lebih sempit.','REPORT_TOO_LARGE');const date=Utilities.formatDate(new Date(),APP.TIME_ZONE,'yyyyMMdd-HHmmss'),filename='pemilih-muda-'+value.toLowerCase().replace(/_/g,'-')+'-'+date+'.csv';logActivity_(admin.user.UserID,'ADMIN_UPDATE','Report',value,'Export laporan '+value+' ('+data.rows.length+' baris)','');return apiSuccess_({filename:filename,mimeType:'text/csv;charset=utf-8',content:csvFromRows_(data.headers,data.rows),rows:data.rows.length},'Laporan CSV berhasil dibuat.');}catch(error){console.error(error);return apiError_(error.publicCode?error.message:'Laporan gagal dibuat.',error.publicCode||'REPORT_EXPORT_FAILED');}}
