function compareWinnerCandidates_(left,right){return Number(right.point)-Number(left.point)||Number(right.correct)-Number(left.correct)||Number(right.quizCompleted)-Number(left.quizCompleted)||Number(right.averageScore)-Number(left.averageScore);}

function sameWinnerMetrics_(left,right){return Boolean(left&&right)&&Number(left.point)===Number(right.point)&&Number(left.correct)===Number(right.correct)&&Number(left.quizCompleted)===Number(right.quizCompleted)&&Number(left.averageScore)===Number(right.averageScore);}

function fraudRisk_(score){const value=Number(score||0);return value>=51?'HIGH RISK':value>=21?'REVIEW':'NORMAL';}

function buildWinnerCandidates_(seasonId){
  const users=readTable_('Users').filter(item=>item.Role==='STUDENT'&&item.Status==='ACTIVE'),schools=readTable_('Schools').reduce((map,item)=>{map[item.SchoolID]=item.NamaSekolah;return map;},{}),points=readTable_('PointTransactions').filter(item=>item.Status==='VALID'&&item.SeasonID===seasonId).reduce((map,item)=>{map[item.UserID]=(map[item.UserID]||0)+Number(item.Point||0);return map;},{}),sessions=readTable_('QuizSessions').filter(item=>item.Status==='COMPLETED'&&item.SeasonID===seasonId),sessionStats=sessions.reduce((map,item)=>{if(!map[item.UserID])map[item.UserID]={correct:0,completed:0,scoreTotal:0};map[item.UserID].correct+=Number(item.Correct||0);map[item.UserID].completed+=1;map[item.UserID].scoreTotal+=Number(item.Score||0);return map;},{}),disqualified=new Set(readTable_('Winners').filter(item=>item.SeasonID===seasonId&&item.SelectionStatus==='DISQUALIFIED').map(item=>item.UserID));
  const rows=users.filter(user=>!disqualified.has(user.UserID)&&sessionStats[user.UserID]&&sessionStats[user.UserID].completed>0).map(user=>{const stat=sessionStats[user.UserID];return {userId:user.UserID,name:user.Name,publicName:maskPublicName_(user.Name),school:schools[user.SchoolID]||'',point:Number(points[user.UserID]||0),correct:stat.correct,quizCompleted:stat.completed,averageScore:Math.round(stat.scoreTotal/stat.completed*100)/100,fraudScore:Number(user.FraudScore||0),fraudRisk:fraudRisk_(user.FraudScore)};}).sort(compareWinnerCandidates_);
  let rank=0,previous=null;return rows.map((item,index)=>{if(!sameWinnerMetrics_(item,previous))rank=index+1;previous=item;return Object.assign({rank:rank},item);});
}

function seasonFinalizable_(season){const today=Utilities.formatDate(new Date(),APP.TIME_ZONE,'yyyy-MM-dd');return ['FINISHED','ARCHIVED'].indexOf(season.Status)>=0||dateOnly_(season.TanggalSelesai)<today;}

function getWinnerCandidates(adminToken,seasonId){
  try{requireSession_(adminToken,['ADMIN','SUPERADMIN']);const id=sanitizeText_(seasonId,40),season=findOne_('Seasons','SeasonID',id);if(!season)return apiError_('Season tidak ditemukan.','SEASON_NOT_FOUND');const candidates=buildWinnerCandidates_(id),completed=readTable_('QuizSessions').filter(item=>item.SeasonID===id&&item.Status==='COMPLETED'),status=candidates.length>1&&sameWinnerMetrics_(candidates[0],candidates[1])?'NEED_REVIEW':candidates.length?'READY':'NO_CANDIDATE',winner=readTable_('Winners').find(item=>item.SeasonID===id&&item.SelectionStatus==='VALIDATED')||null;return apiSuccess_({season:{id:id,name:season.NamaSeason,status:season.Status,start:season.TanggalMulai,end:season.TanggalSelesai,reward:season.Reward,finalizable:seasonFinalizable_(season)},summary:{participants:new Set(completed.map(item=>item.UserID)).size,quizCompleted:completed.length,totalActivity:completed.length},status:status,candidates:candidates.slice(0,10),winner:winner});}catch(error){return apiError_(error.message,error.publicCode||'WINNER_CANDIDATES_FAILED');}
}

function finalizeWinner(adminToken,payload){
  try{const admin=requireSession_(adminToken,['ADMIN','SUPERADMIN']),data=payload||{},seasonId=sanitizeText_(data.seasonId,40),userId=sanitizeText_(data.userId,40),action=sanitizeText_(data.action,20).toUpperCase(),reason=sanitizeText_(data.reason,500);if(['VALIDATE','DISQUALIFY'].indexOf(action)<0)return apiError_('Tindakan tidak valid.','VALIDATION_ERROR');if(action==='DISQUALIFY'&&reason.length<5)return apiError_('Alasan diskualifikasi wajib diisi.','DISQUALIFY_REASON_REQUIRED');return withDocumentLock_(function(){const season=findOne_('Seasons','SeasonID',seasonId);if(!season)return apiError_('Season tidak ditemukan.','SEASON_NOT_FOUND');if(!seasonFinalizable_(season))return apiError_('Season belum selesai dan belum dapat difinalisasi.','SEASON_NOT_FINALIZABLE');const decisions=readTable_('Winners').filter(item=>item.SeasonID===seasonId);if(decisions.some(item=>item.SelectionStatus==='VALIDATED'))return apiError_('Pemenang season sudah ditetapkan.','WINNER_ALREADY_SELECTED');if(decisions.some(item=>item.UserID===userId&&item.SelectionStatus==='DISQUALIFIED'))return apiError_('Kandidat sudah didiskualifikasi.','ALREADY_DISQUALIFIED');const candidates=buildWinnerCandidates_(seasonId),candidate=candidates.find(item=>item.userId===userId);if(!candidate)return apiError_('Kandidat tidak ditemukan.','CANDIDATE_NOT_FOUND');if(action==='VALIDATE'&&!sameWinnerMetrics_(candidate,candidates[0]))return apiError_('Hanya kandidat peringkat teratas atau kandidat tie yang dapat divalidasi.','CANDIDATE_NOT_TOP');const timestamp=nowIso_(),winnerId=generateId_('Winners'),record={WinnerID:winnerId,SeasonID:seasonId,UserID:userId,Rank:candidate.rank,Point:candidate.point,Reward:season.Reward,StatusReward:'WAITING',SelectionStatus:action==='VALIDATE'?'VALIDATED':'DISQUALIFIED',ReviewNote:reason,SelectedAt:timestamp,SelectedBy:admin.user.UserID};appendRecords_('Winners',[record]);logActivity_(admin.user.UserID,action==='VALIDATE'?'ADMIN_UPDATE':'DISQUALIFY','Winners',winnerId,(action==='VALIDATE'?'Menetapkan pemenang':'Diskualifikasi kandidat')+(reason?' — '+reason:''),'');CacheService.getScriptCache().remove('publicWinners');return apiSuccess_({winnerId:winnerId,status:record.SelectionStatus},action==='VALIDATE'?'Pemenang berhasil ditetapkan.':'Kandidat berhasil didiskualifikasi.');});}catch(error){console.error(error);return apiError_(error.publicCode?error.message:'Finalisasi pemenang gagal.',error.publicCode||'WINNER_FINALIZE_FAILED');}
}

function publicWinners_(){const cache=CacheService.getScriptCache(),cached=cache.get('publicWinners');if(cached)return JSON.parse(cached);const users=readTable_('Users').reduce((map,item)=>{map[item.UserID]=item;return map;},{}),schools=readTable_('Schools').reduce((map,item)=>{map[item.SchoolID]=item.NamaSekolah;return map;},{}),seasons=readTable_('Seasons').reduce((map,item)=>{map[item.SeasonID]=item.NamaSeason;return map;},{}),rows=readTable_('Winners').filter(item=>item.SelectionStatus==='VALIDATED').sort((a,b)=>String(b.SelectedAt).localeCompare(String(a.SelectedAt))).map(item=>{const user=users[item.UserID]||{};return {winnerId:item.WinnerID,seasonId:item.SeasonID,season:seasons[item.SeasonID]||'',name:maskPublicName_(user.Name),school:schools[user.SchoolID]||'',point:Number(item.Point||0),reward:item.Reward,statusReward:item.StatusReward,selectedAt:item.SelectedAt};});cache.put('publicWinners',JSON.stringify(rows),APP.CACHE_SECONDS);return rows;}

function getPublicWinners(limit){try{return apiSuccess_({winners:publicWinners_().slice(0,Math.min(12,Math.max(1,Number(limit)||6)))});}catch(error){return apiError_('Data pemenang belum tersedia.','WINNERS_UNAVAILABLE');}}
